version: '3'
services:
  temperature_app:
    image: temperature_app  # Reference the image built using Dockerfile
    ports:
      - "5000:5000"
      - "8000:8000"                                 
    environment: 
      - FLASK_PORT=5000
      - METRICS_PORT=8000      
    container_name: temperature_app
    depends_on:
      - prometheus                   
      - grafana                      
    networks:
      - monitoring               
    restart: always               

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring:/etc/prometheus/
    ports:
      - "9090:9090"                 
    networks:
      - monitoring                   
    restart: always
      
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"                
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin   
    depends_on:
      - prometheus                   
    networks:
      - monitoring                   
    restart: always                  
networks:
  monitoring:
    driver: bridge
